# KNP-EMI Config File
problem_type : "KNP-EMI"

# Input and output directorie
input_dir  : '/home/hherlyng/knp-emi-cgx/src/CGx/KNPEMI/input/'
output_dir : '/global/D1/homes/hherlyng/knp-emi-cgx/output/GC/20m/200c/T_stim=1000ms_iterative_study/'

# Numerical parameters 
dt : 0.00005 # Timestep size 
time_steps : 100 # Number of timesteps
# T  : 5e-3 # Simulation end time

# Problem constants (in consistent units)
physical_constants:
  T : 300   # Temperature [K]
  F : 96485 # Faraday constant [C/mol]
  R : 8.314 # Gas constant [J/(K*mol)]

C_M : 0.01 # membrane capacitance

# Mesh and meshtags files 
mesh_file      : "geometries/GC/20m/200c/mesh.xdmf"
cell_tag_file  : "geometries/GC/20m/200c/mesh.xdmf"
facet_tag_file : "geometries/GC/20m/200c/facets.xdmf"
mesh_conversion_factor: 1e-9

ics_tags  : !range [2, 202]  # Intracellular space cell tags
ecs_tags  : [1] # Extracellular space cell tags
boundary_tags : !range [1001, 1202]  # Boundary facet tags
membrane_tags : !range [2, 202] # Membrane (interface) facet tags
stimulus_tags : [129] # Membrane facet tags of the cells being stimulated
membrane_data_tag : 129 # Tag for which membrane data is written to file

point_evaluation :
  ics_points : [[1200, 3102, 3497], [1200, 3302, 3476]]
  ecs_points : [[1200, 3113, 3607], [1200, 1334, 3934]]

stimulus :
  conductance :
    g_syn_bar : 4.0e-10 # 0.5e-10 # Maximum synaptic conductance
  a_syn : 5e-4 # Synaptic time constant
  T_stim : 1000e-3 # Stimulus period, high freq = 20 ms, normal freq = 1 s
  scale : True

solver :
  direct : False
  output :
    save_xdmf : False
    save_cpoints : False
    save_pngs : True
    save_dat : True