# KNP-EMI Config File
problem_type : "KNP-EMI"

# Input and output directories
input_dir  : '/home/hherlyng/knp-emi-cgx/src/CGx/KNPEMI/input/'
output_dir : '/global/D1/homes/hherlyng/knp-emi-cgx/output/GC/10m/100c/T_stim=1000ms_iterative_study/'

# Numerical parameters 
dt : 0.00001 # Timestep size 
time_steps : 400 # Number of timesteps
# T  : 5e-3 # Simulation end time

# Problem constants (in consistent units)
physical_constants:
  T : 300   # Temperature [K]
  F : 96485 # Faraday constant [C/mol]
  R : 8.314 # Gas constant [J/(K*mol)]

C_M : 0.01 # membrane capacitance [F/m^2]

# Mesh and meshtags files 
mesh_file      : "geometries/GC/10m/100c/mesh.xdmf"
cell_tag_file  : "geometries/GC/10m/100c/mesh.xdmf"
facet_tag_file : "geometries/GC/10m/100c/facets.xdmf"
mesh_conversion_factor: 1e-9

ics_tags  : !range [2, 102] # Intracellular space cell tags 
ecs_tags  : [1] # Extracellular space cell tags
boundary_tags : !range [1001, 1102] # Boundary facet tags
membrane_tags : !range [2, 102] # Membrane (interface) facet tags
stimulus_tags : [46] # Membrane facet tags of the cells being stimulated
membrane_data_tag : 46 # Tag for which membrane data is written to file

point_evaluation :
  ics_points : [[3345.33, 6703.67, 7112.84]]
  ecs_points : [[3345.33, 6413.21, 7412.65]]

stimulus :
  conductance :
    g_syn_bar : 60 # Maximum synaptic conductance [S/m^2]
  a_syn : 5e-4 # Synaptic time constant
  T_stim : 1000e-3 # Stimulus period, high freq = 20 ms, normal freq = 1 s
  scale : False

solver :
  direct : False
  output :
    save_xdmf : False
    save_cpoints : False
    save_pngs : True
    save_dat : True